// This file was auto-generated by prisma-generator-typescript-interfaces

export type UserStatus = "ACTIVE" | "INACTIVE" | "SUSPENDED";

export interface User {
  id: string;
  email: EmailType;
  name: string | null;
  status: UserStatus;
  createdAt: MyDate;
  updatedAt: MyDate;
  posts?: Post[];
  profile?: Profile | null;
}

export interface Profile {
  id: string;
  bio: string | null;
  avatar: { url: string; width: number; height: number; } | null;
  user?: User;
  userId: string;
}

export interface Post {
  id: string;
  title: string;
  content: string;
  published: boolean;
  createdAt: Date;
  updatedAt: Date;
  author?: User;
  authorId: string;
  meta: JsonValue;
}

export interface Address {
  street: string;
  city: string;
  state: string;
  zipCode: string;
  country: string;
}

type EmailType = { address: string; domain: string };

type MyDate = { time: number };

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
