// This file was auto-generated by prisma-generator-typescript-interfaces

export type UserStatus = "ACTIVE" | "INACTIVE" | "SUSPENDED";

export interface User {
  id: string;
  email: string;
  name: string | null;
  status: UserStatus;
  createdAt: Date;
  updatedAt: Date;
  posts?: Post[];
  profile?: Profile | null;
}

export interface Profile {
  id: string;
  bio: string | null;
  avatar: string | null;
  user?: User;
  userId: string;
}

export interface Post {
  id: string;
  title: string;
  content: string;
  published: boolean;
  createdAt: Date;
  updatedAt: Date;
  author?: User;
  authorId: string;
}

export interface Address {
  street: string;
  city: string;
  state: string;
  zipCode: string;
  country: string;
}
