// This file was auto-generated by prisma-generator-typescript-interfaces

export type Gender = "Male" | "Female" | "Other";

export type PhotoType = "Selfie" | "Profile" | "Tagged";

export type Person = {
  id: number;
  name: string;
  gender: Gender;
  addressId: number;
  address?: Address;
  photos: Photo[];
  tags: Tag | null;
};

export type Address = {
  id: number;
  addressText: string;
  people?: Person[];
};

export type Photo = {
  height: number;
  Width: number;
  url: string;
  type: PhotoType;
};

export type Tag = {
  id: number;
  name: string;
};
