// This file was auto-generated by prisma-generator-typescript-interfaces

export type Gender = "Male" | "Female" | "Other";

export type DataTest = "Apple" | "Banana" | "Orange" | "Pear";

export interface Person {
  id: Decimal;
  name: ArrayObject;
  age: Decimal;
  email: ArrayObject | null;
  gender: Gender;
  addressId: Decimal;
  address?: Address;
  friends?: Person[];
  friendsOf?: Person[];
  data?: Data | null;
}

export interface Address {
  id: Decimal;
  streetNumber: Decimal;
  streetName: ArrayObject;
  city: ArrayObject;
  isBilling: BufferObject;
  people?: Person[];
}

export interface Data {
  id: ArrayObject;
  stringField: ArrayObject;
  booleanField: BufferObject;
  intField: Decimal;
  floatField: JsonValue;
  jsonField: JsonValue;
  dateField: Date;
  bigIntField: bigint;
  decimalField: Decimal;
  bytesField: Uint8Array;
  enumField: DataTest;
  optionalStringField: ArrayObject | null;
  optionalBooleanField: BufferObject | null;
  optionalIntField: Decimal | null;
  optionalFloatField: JsonValue | null;
  optionalJsonField: JsonValue | null;
  optionalDateField: Date | null;
  optionalBigIntField: bigint | null;
  optionalDecimalField: Decimal | null;
  optionalBytesField: Uint8Array | null;
  optionalEnumField: DataTest | null;
  stringArrayField: ArrayObject[];
  booleanArrayField: BufferObject[];
  intArrayField: Decimal[];
  floatArrayField: JsonValue[];
  jsonArrayField: JsonValue[];
  dateArrayField: Date[];
  bigIntArrayField: bigint[];
  decimalArrayField: Decimal[];
  bytesArrayField: Uint8Array[];
  enumArrayField: DataTest[];
  personId: Decimal;
  person?: Person;
}

type Decimal = { valueOf(): string };

type ArrayObject = { [index: number]: number } & { length?: never };

type BufferObject = { type: "Buffer"; data: number[] };

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
