// This file was auto-generated by prisma-generator-typescript-interfaces

export type Gender = "Male" | "Female" | "Other";

export type DataTest = "Apple" | "Banana" | "Orange" | "Pear";

export interface Person {
  id: number;
  name: Decimal;
  age: number;
  email: Decimal | null;
  gender: Gender;
  addressId: number;
  address?: Address;
  friends?: Person[];
  friendsOf?: Person[];
  data?: Data | null;
}

export interface Address {
  id: number;
  streetNumber: number;
  streetName: Decimal;
  city: Decimal;
  isBilling: JsonValue;
  people?: Person[];
}

export interface Data {
  id: Decimal;
  stringField: Decimal;
  booleanField: JsonValue;
  intField: number;
  floatField: number;
  jsonField: JsonValue;
  dateField: Date;
  bigIntField: bigint;
  decimalField: Decimal;
  bytesField: Uint8Array;
  enumField: DataTest;
  optionalStringField: Decimal | null;
  optionalBooleanField: JsonValue | null;
  optionalIntField: number | null;
  optionalFloatField: number | null;
  optionalJsonField: JsonValue | null;
  optionalDateField: Date | null;
  optionalBigIntField: bigint | null;
  optionalDecimalField: Decimal | null;
  optionalBytesField: Uint8Array | null;
  optionalEnumField: DataTest | null;
  stringArrayField: Decimal[];
  booleanArrayField: JsonValue[];
  intArrayField: number[];
  floatArrayField: number[];
  jsonArrayField: JsonValue[];
  dateArrayField: Date[];
  bigIntArrayField: bigint[];
  decimalArrayField: Decimal[];
  bytesArrayField: Uint8Array[];
  enumArrayField: DataTest[];
  personId: number;
  person?: Person;
}

type Decimal = { valueOf(): string };

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
