// This file was auto-generated by prisma-generator-typescript-interfaces

import { A, Aa, AAA, ab, Ba, ccc, Ccc, CCC, Last } from "../types.js";

export type Gender = "Male" | "Female" | "Other";

export type DataTest = "Apple" | "Banana" | "Orange" | "Pear";

export interface Person {
  id: CCC;
  name: Aa;
  age: CCC;
  email: Aa | null;
  gender: Gender;
  addressId: CCC;
  address?: Address;
  friends?: Person[];
  friendsOf?: Person[];
  data?: Data | null;
}

export interface Address {
  id: CCC;
  streetNumber: CCC;
  streetName: Aa;
  city: Aa;
  isBilling: Ba;
  people?: Person[];
}

export interface Data {
  id: Aa;
  stringField: Aa;
  booleanField: Ba;
  intField: CCC;
  floatField: A;
  jsonField: AAA;
  dateField: Ccc;
  bigIntField: ccc;
  decimalField: ab;
  bytesField: Last;
  enumField: DataTest;
  optionalStringField: Aa | null;
  optionalBooleanField: Ba | null;
  optionalIntField: CCC | null;
  optionalFloatField: A | null;
  optionalJsonField: AAA | null;
  optionalDateField: Ccc | null;
  optionalBigIntField: ccc | null;
  optionalDecimalField: ab | null;
  optionalBytesField: Last | null;
  optionalEnumField: DataTest | null;
  stringArrayField: Aa[];
  booleanArrayField: Ba[];
  intArrayField: CCC[];
  floatArrayField: A[];
  jsonArrayField: AAA[];
  dateArrayField: Ccc[];
  bigIntArrayField: ccc[];
  decimalArrayField: ab[];
  bytesArrayField: Last[];
  enumArrayField: DataTest[];
  personId: CCC;
  person?: Person;
}
