// This file was auto-generated by prisma-generator-typescript-interfaces

import { Aa, ab, Ba } from "./path/to/CustomTypesA.js"
import { A, AA, AAA } from "./path/to/CustomTypesB.js"
import { lowerFile } from "./path/to/customTypesC.js"
import { UpperFile } from "./path/to/CustomTypesC.js"
import { Last } from "./path/to/CustomTypesD.js"

export type Gender = "Male" | "Female" | "Other";

export type DataTest = "Apple" | "Banana" | "Orange" | "Pear";

export interface Person {
  id: ab;
  name: Aa;
  age: ab;
  email: Aa | null;
  gender: Gender;
  addressId: ab;
  address?: Address;
  friends?: Person[];
  friendsOf?: Person[];
  data?: Data | null;
}

export interface Address {
  id: ab;
  streetNumber: ab;
  streetName: Aa;
  city: Aa;
  isBilling: Ba;
  people?: Person[];
}

export interface Data {
  id: Aa;
  stringField: Aa;
  booleanField: Ba;
  intField: ab;
  floatField: A;
  jsonField: AAA;
  dateField: AA;
  bigIntField: UpperFile;
  decimalField: lowerFile;
  bytesField: Last;
  enumField: DataTest;
  optionalStringField: Aa | null;
  optionalBooleanField: Ba | null;
  optionalIntField: ab | null;
  optionalFloatField: A | null;
  optionalJsonField: AAA | null;
  optionalDateField: AA | null;
  optionalBigIntField: UpperFile | null;
  optionalDecimalField: lowerFile | null;
  optionalBytesField: Last | null;
  optionalEnumField: DataTest | null;
  stringArrayField: Aa[];
  booleanArrayField: Ba[];
  intArrayField: ab[];
  floatArrayField: A[];
  jsonArrayField: AAA[];
  dateArrayField: AA[];
  bigIntArrayField: UpperFile[];
  decimalArrayField: lowerFile[];
  bytesArrayField: Last[];
  enumArrayField: DataTest[];
  personId: ab;
  person?: Person;
}
