// This file was auto-generated by prisma-generator-typescript-interfaces

import {
  ImportedBigInt,
  ImportedBoolean,
  ImportedBytes,
  ImportedDate,
  ImportedDecimal,
  ImportedFloat,
  ImportedInt,
  ImportedJson,
  ImportedString,
} from "../types.js";

export type Gender = "Male" | "Female" | "Other";

export type DataTest = "Apple" | "Banana" | "Orange" | "Pear";

export interface Person {
  id: ImportedInt;
  name: ImportedString;
  age: ImportedInt;
  email: ImportedString | null;
  gender: Gender;
  addressId: ImportedInt;
  address?: Address;
  friends?: Person[];
  friendsOf?: Person[];
  data?: Data | null;
}

export interface Address {
  id: ImportedInt;
  streetNumber: ImportedInt;
  streetName: ImportedString;
  city: ImportedString;
  isBilling: ImportedBoolean;
  people?: Person[];
}

export interface Data {
  id: ImportedString;
  stringField: ImportedString;
  booleanField: ImportedBoolean;
  intField: ImportedInt;
  floatField: ImportedFloat;
  jsonField: ImportedJson;
  dateField: ImportedDate;
  bigIntField: ImportedBigInt;
  decimalField: ImportedDecimal;
  bytesField: ImportedBytes;
  enumField: DataTest;
  optionalStringField: ImportedString | null;
  optionalBooleanField: ImportedBoolean | null;
  optionalIntField: ImportedInt | null;
  optionalFloatField: ImportedFloat | null;
  optionalJsonField: ImportedJson | null;
  optionalDateField: ImportedDate | null;
  optionalBigIntField: ImportedBigInt | null;
  optionalDecimalField: ImportedDecimal | null;
  optionalBytesField: ImportedBytes | null;
  optionalEnumField: DataTest | null;
  stringArrayField: ImportedString[];
  booleanArrayField: ImportedBoolean[];
  intArrayField: ImportedInt[];
  floatArrayField: ImportedFloat[];
  jsonArrayField: ImportedJson[];
  dateArrayField: ImportedDate[];
  bigIntArrayField: ImportedBigInt[];
  decimalArrayField: ImportedDecimal[];
  bytesArrayField: ImportedBytes[];
  enumArrayField: DataTest[];
  personId: ImportedInt;
  person?: Person;
}
