// This file was auto-generated by prisma-generator-typescript-interfaces

export type Gender = "Male" | "Female" | "Other";

export interface Person {
  id: DefinedInt;
  name: "constant string";
  age: DefinedInt;
  email: "constant string" | null;
  gender: Gender;
  addressId: DefinedInt;
  address?: Address;
  friendsOf?: Person[];
  friends?: Person[];
  data?: Data | null;
}

export interface Address {
  id: DefinedInt;
  streetNumber: DefinedInt;
  streetName: "constant string";
  city: "constant string";
  isBilling: boolean;
  people?: Person[];
}

export interface Data {
  id: "constant string";
  stringField: "constant string";
  booleanField: boolean;
  intField: DefinedInt;
  bigIntField: bigint;
  floatField: number;
  decimalField: Decimal;
  dateField: Date;
  jsonField: JsonValue;
  bytesField: Uint8Array;
  customField: JsonValue;
  optionalStringField: "constant string" | null;
  optionalBooleanField: boolean | null;
  optionalIntField: DefinedInt | null;
  optionalBigIntField: bigint | null;
  optionalFloatField: number | null;
  optionalDecimalField: Decimal | null;
  optionalDateField: Date | null;
  optionalJsonField: JsonValue | null;
  optionalBytesField: Uint8Array | null;
  optionalCustomField: JsonValue | null;
  stringArrayField: "constant string"[];
  booleanArrayField: boolean[];
  intArrayField: DefinedInt[];
  bigIntArrayField: bigint[];
  floatArrayField: number[];
  decimalArrayField: Decimal[];
  dateArrayField: Date[];
  jsonArrayField: JsonValue[];
  bytesArrayField: Uint8Array[];
  customArrayField: JsonValue[];
  personId: DefinedInt;
  person?: Person;
}

type DefinedInt = number;

type Decimal = { valueOf(): string };

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
