// This file was auto-generated by prisma-generator-typescript-interfaces

export interface User {
  id: string;
  name: string;
  email: string;
  data: JsonValue;
  createdAt: Date;
  updatedAt: Date;
}

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
