import type { GeneratorConfig } from "@prisma/generator-helper";

export interface Config {
  enumPrefix: string;
  enumSuffix: string;
  enumObjectPrefix: string;
  enumObjectSuffix: string;
  modelPrefix: string;
  modelSuffix: string;
  typePrefix: string;
  typeSuffix: string;
  headerComment: string;
  modelType: "interface" | "type";

  // enumType: "stringUnion" | "enum" | "object";
  // dateType: "Date" | "string" | "number";
  // bigIntType: "bigint" | "string" | "number";
  // decimalType: "Decimal" | "string" | "number";
  // bytesType: "Uint8Array" | "Buffer" | "ArrayObject" | "BufferObject" | "string" | "number[]";

  enumType: "stringUnion" | "enum" | "object";
  stringType: string;
  booleanType: string;
  intType: string;
  floatType: string;
  jsonType: string;
  dateType: string;
  bigIntType: string;
  decimalType: string;
  bytesType: string;

  exportEnums: boolean;
  optionalRelations: boolean;
  omitRelations: boolean;
  optionalNullables: boolean;
  prettier: boolean;
  resolvePrettierConfig: boolean;
}

class ConfigValidator {
  public errors: string[] = [];

  constructor(private generatorConfig: GeneratorConfig["config"]) {}

  public validate(config: Config): Config {
    if (!["interface", "type"].includes(config.modelType)) {
      this.errors.push(`Invalid modelType: ${config.modelType}`);
    }
    if (!["stringUnion", "enum", "object"].includes(config.enumType)) {
      this.errors.push(`Invalid enumType: ${config.enumType}`);
    }
    // if (!["Date", "string", "number"].includes(config.dateType)) {
    //   this.errors.push(`Invalid dateType: ${config.dateType}`);
    // }
    // if (!["bigint", "string", "number"].includes(config.bigIntType)) {
    //   this.errors.push(`Invalid bigIntType: ${config.bigIntType}`);
    // }
    // if (!["Decimal", "string", "number"].includes(config.decimalType)) {
    //   this.errors.push(`Invalid decimalType: ${config.decimalType}`);
    // }
    // if (
    //   !["Uint8Array", "Buffer", "ArrayObject", "BufferObject", "string", "number[]"].includes(
    //     config.bytesType,
    //   )
    // ) {
    //   this.errors.push(`Invalid bytesType: ${config.bytesType}`);
    // }

    return config;
  }

  public boolean(name: keyof Config, defaultValue: boolean) {
    const value = this.generatorConfig[name];
    if (typeof value === "undefined") {
      return defaultValue;
    } else if (typeof value === "string") {
      const valueLower = value.toLowerCase();
      if (valueLower === "true") {
        return true;
      } else if (valueLower === "false") {
        return false;
      }
    }

    this.errors.push(`Invalid ${name}: ${value}`);
    return defaultValue;
  }
}

export function getConfig(generatorConfig: GeneratorConfig["config"]): Config {
  const validator = new ConfigValidator(generatorConfig);
  const config = validator.validate({
    // Defaults
    enumPrefix: "",
    enumSuffix: "",
    enumObjectPrefix: "",
    enumObjectSuffix: "",
    modelPrefix: "",
    modelSuffix: "",
    typePrefix: "",
    typeSuffix: "",
    headerComment: "This file was auto-generated by prisma-generator-typescript-interfaces",
    modelType: "interface",

    // Default types
    stringType: "string",
    booleanType: "boolean",
    intType: "number",
    floatType: "number",
    jsonType: "JsonValue",
    enumType: "stringUnion",
    dateType: "Date",
    bigIntType: "bigint",
    decimalType: "Decimal",
    bytesType: "Uint8Array",

    // User config
    ...generatorConfig,

    // Booleans at the end since in the generator config they are strings
    exportEnums: validator.boolean("exportEnums", true),
    optionalRelations: validator.boolean("optionalRelations", true),
    omitRelations: validator.boolean("omitRelations", false),
    optionalNullables: validator.boolean("optionalNullables", false),
    prettier: validator.boolean("prettier", false),
    resolvePrettierConfig: validator.boolean("resolvePrettierConfig", true),
  });

  if (validator.errors.length) {
    throw new Error(validator.errors.join("\n"));
  }

  return config;
}
