name: Publish package

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            TAG="latest"
          elif [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-(alpha|beta|rc)\.[0-9]+$ ]]; then
            TAG=$(echo "$VERSION" | cut -d'-' -f2 | cut -d'.' -f1)
          else
            echo "Version format not supported: $VERSION"
            exit 1
          fi
          echo "NPM_TAG=$TAG" >> $GITHUB_ENV
      - run: npm publish --tag ${{ env.NPM_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
